version: '3'

services:
  dev:
    image: golang:1.18-bullseye
    volumes:
      - ./:/go/src/github.com/big-cabbage/lo
    working_dir: /go/src/github.com/big-cabbage/lo
    command: make watch-test
